### ISSUE TITLE
XPath expression: String before colon interpreted as prefix

### ISSUE THREAD

**Issue by ktk** [mmlab/RMLProcessor#5]
While transforming an XML file I run into an exception:

    [RMLEngine:generateRDFTriples] Generate RDF triples for file:/Users/ktk/workspace/zazuko.bfs/eCH0071_150101.ttl#Canton
    Feb 22, 2015 10:13:51 PM be.ugent.mmlab.rml.processor.concrete.XPathProcessor execute
    SEVERE: null
    org.jaxen.saxpath.SAXPathException: undeclared prefix: eCH-0071
      at jlibs.xml.sax.dog.sniff.XPathParser.startNameStep(XPathParser.java:205)
      at org.jaxen.saxpath.base.XPathReader.nameTest(XPathReader.java:713)
      at org.jaxen.saxpath.base.XPathReader.nodeTest(XPathReader.java:592)
      at org.jaxen.saxpath.base.XPathReader.step(XPathReader.java:541)
      at org.jaxen.saxpath.base.XPathReader.steps(XPathReader.java:442)
      at org.jaxen.saxpath.base.XPathReader.absoluteLocationPath(XPathReader.java:370)
      at org.jaxen.saxpath.base.XPathReader.locationPath(XPathReader.java:326)
      at org.jaxen.saxpath.base.XPathReader.pathExpr(XPathReader.java:185)
      at org.jaxen.saxpath.base.XPathReader.unionExpr(XPathReader.java:1006)
      at org.jaxen.saxpath.base.XPathReader.unaryExpr(XPathReader.java:994)
      at org.jaxen.saxpath.base.XPathReader.multiplicativeExpr(XPathReader.java:943)
      at org.jaxen.saxpath.base.XPathReader.additiveExpr(XPathReader.java:913)
      at org.jaxen.saxpath.base.XPathReader.relationalExpr(XPathReader.java:860)
      at org.jaxen.saxpath.base.XPathReader.equalityExpr(XPathReader.java:829)
      at org.jaxen.saxpath.base.XPathReader.andExpr(XPathReader.java:809)
      at org.jaxen.saxpath.base.XPathReader.orExpr(XPathReader.java:787)
      at org.jaxen.saxpath.base.XPathReader.expr(XPathReader.java:780)
      at org.jaxen.saxpath.base.XPathReader.parse(XPathReader.java:100)
      at jlibs.xml.sax.dog.sniff.XPathParser.parse(XPathParser.java:80)
      at jlibs.xml.sax.dog.XMLDog.addXPath(XMLDog.java:78)
      at be.ugent.mmlab.rml.processor.concrete.XPathProcessor.execute(XPathProcessor.java:131)
      at be.ugent.mmlab.rml.core.RMLEngine.generateRDFTriples(RMLEngine.java:169)
      at be.ugent.mmlab.rml.core.RMLEngine.runRMLMapping(RMLEngine.java:115)
      at be.ugent.mmlab.rml.main.Main.main(Main.java:44)

After debugging I figured out the problem is in [Line 21](https://gist.github.com/ktk/1df91a3d8e281ac9575d#file-ech0071_150101-ttl-L21) of this sample:

    rml:iterator "/eCH-0071:nomenclature/cantons/canton" ];

It seems that the XPath value gets interpreted and somehow it tries to interpret the string before the colon (`:`) as prefix.

The XML file starts like this:

    <?xml version="1.0" encoding="UTF-8"?>
    <eCH-0071:nomenclature xmlns:eCH-0071="http://www.ech.ch/xmlns/eCH-0071/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ech.ch/xmlns/eCH-0071/1 http://www.ech.ch/xmlns/eCH-0071/1/eCH-0071-1-1.xsd">
      <validFrom>2015-01-01</validFrom>
    <cantons>
      <canton>
        <cantonId>1</cantonId>
        <cantonAbbreviation>ZH</cantonAbbreviation>
        <cantonLongName>Zürich</cantonLongName>
        <cantonDateOfChange>1960-01-01</cantonDateOfChange>
      </canton>

Sample data: https://gist.github.com/ktk/cc6a88adfe80f3a27207
Sample transformation: https://gist.github.com/ktk/1df91a3d8e281ac9575d

**Comment by mielvds** [comment]
Hmm that exception should be caught of course, but your problem is a limitation of the XPath library we use. It doesn't automatically detect namespaces in XML documents, which is probably a results of the streaming parser. You'll have to declare the namespaces beforehand like here https://github.com/mmlab/RMLProcessor/blob/master/src/main/java/be/ugent/mmlab/rml/processor/concrete/XPathProcessor.java#L57.
This isn't pretty, so we'll look into a long term solution in the mean time.

**Comment by ktk** [comment]
ok thanks for the remarks. If I get that correctly I should be able to get rid of it if I add a namespace for `eCH-0071` to the source for the moment?

**Comment by andimou** [comment]
Fixed with f8a978db3d5638df4608bc0ac85edd84317c8129
